### PR TITLE
Port wc(1)

### PR DESCRIPTION
**Pull request by q66**

### CODE REVIEW

**Comment by dcantrell** [comment]
I've added in libxo as a df(1) requirement.  libxo is a 2-clause BSD licensed library from Juniper Networks.  Given that, I decided to add it as a requirement since df uses it.  I based my df patch on what I did porting OpenBSD, but I am still finalizing some things.  I'm pushing it now since you have a port of wc and that uses libxo as well, so I would like to use it there too.

**Comment by q66** [comment]
hm, okay...

libxo has some issues building on musl, and its tarball configure is broken, it's workaroundable though so i'll re-add libxo here and maybe submit fixes upstream later

**Comment by q66** [comment]
updated to use libxo

**Comment by q66** [comment]
here's the libxo musl patch, by the way https://github.com/chimera-linux/cports/blob/master/srcpkgs/libxo/patches/musl.patch

**Comment by q66** [comment]
oh, but you might not need it on Alpine - maybe you can get away with simply installing `bsd-compat-headers` when building it

**Comment by q66** [comment]
https://github.com/Juniper/libxo/pull/82 + `bsd-compat-headers` and you should be good to go

**Pull request merged**
