### PR TITLE
Fix github CI script, glibc build

### PR DESCRIPTION
**Pull request by q66**
Not yet sure if this one will work, might need a few attempts.

### CODE REVIEW

**Comment by q66** [comment]
this one is okay now

**Comment by dcantrell** [comment]
Thanks for this PR.  I just noticed the glibc failures this morning myself.

One request: can you add a license boilerplate block and copyright statement to cdefs.h?  You added the file, so the copyright statement should be your name.  Everything is BSD-3-Clause license that I have added, which is what I would prefer to additional contributions.  You can use the boilerplate from compat.h as a template.

**Comment by q66** [comment]
done

**Comment by dcantrell** [comment]
Looks good, thanks for the updates here.  I appreciate the fixup for CI.

**Pull request merged**
