### PR TITLE
Port du(1)

### PR DESCRIPTION
**Pull request by q66**
While at it, ensure 64-bit file offsets are always used even on 32-bit glibc (on 32-bit musl they are always 64-bit already, but it doesn't harm anything to have the macro defined). This matches freebsd behavior and is relevant here.

### CODE REVIEW

**Comment by dcantrell** [comment]
Strike the siginfo function since we're never going to use that anyway.  I'd also like to see the man page updated to remove any options that we have to remove in these ports.  Also, note the missing options from du in the top level DIFFERENCES file if there is anything new not already mentioned in that file.  Otherwise this looks good.

**Comment by q66** [comment]
what do you mean? there's no siginfo function anymore

**Comment by q66** [comment]
updated manpage/differences

**Comment by dcantrell** [comment]
> what do you mean? there's no siginfo function anymore

My mistake, I was misreading the commit while initially glancing through it.

Looks great!

**Pull request merged**
